Zolociones/Mape/urls.py
from django.conf.urls import url
from maccounts.views import login_view, logout_view
from . import views

urlpatterns = [
    # ex: /mape/
    url(r'^$', views.mape_view, name='mapa'),
    url(r'^login/$', login_view, name='login'),
    url(r'^accounts/$', views.accounts_view, name='accounts'),
    url(r'^e/$', views.shower_view, name='shower'),
    url(r'^event_register/$', views.event_register_view, name='event_register'),
    url(r'^location_register/$', views.location_register_view, name='location_register'),
    url(r'^commertial_register/$', views.commertial_register_view, name='commertial_register'),
    url(r'^$search/$', views.search_view, name='search'),
    url(r'^$logout/$', logout_view, name='maccounts.logout'),
]

Zolociones/Zolociones/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^mape/', include('Mape.urls', namespace="Mape")),
    url(r'^login/', include('maccounts.urls', namespace="Maccounts")),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
        }),
    ]

Zolociones/Mape/models.py
from django.db import models
from django.contrib.auth.models import User, Group
import datetime
from django.utils import timezone
from maccounts.models import User_profile

class Hashtag(models.Model):
	hashtag_name = models.CharField(max_length=45)
	def __unicode__(self):
		return unicode(self.hashtag_name)

class Categorie(models.Model):
	categorie_name = models.CharField(max_length=45, unique=True)
	def __unicode__(self):
		return unicode(self.categorie_name)

class Offer(models.Model):
	offer_name = models.CharField(max_length=45, unique=True)
	price = models.DecimalField(decimal_places=2, max_digits=8, blank=True, null=True )
	product = models.BooleanField(default=True, blank=True)
	image = models.ImageField(upload_to="media", null=True, blank=True)
	def __unicode__(self):
		return unicode(self.offer_name)

class Location(models.Model):
	location_name = models.CharField(max_length=45)
	offers = models.ManyToManyField(Offer, blank=True)
	categories = models.ManyToManyField(Categorie)
	date_joined = models.DateField(null=False, blank=False, auto_now_add=True)
	image = models.ImageField(upload_to="media", null=True, blank=True)
	latitude = models.DecimalField(null=True, decimal_places=15, max_digits=19)
	longitude = models.DecimalField(null=True, decimal_places=15, max_digits=19)
	user_profile = models.ForeignKey(User)
	subscribers = models.ManyToManyField(User_profile, null=False, blank=True)
	def __unicode__(self):
		return unicode(self.location_name)

class Commertial(models.Model):
	commertial_name = models.CharField(max_length=45, unique=True)
	location = models.OneToOneField(Location, on_delete=models.CASCADE)
	ruc = models.BigIntegerField(blank=True, null= True)
	description = models.TextField(null=False, blank=False)
	date_joined = models.DateField(null=False, blank=False, auto_now_add=True)
	commertial_image = models.ImageField(upload_to="accounts", null=True, blank=True)
	user_profile = models.OneToOneField(User_profile)
	def __unicode__(self):
		return unicode(self.commertial_name)

class Event(models.Model):
	event_name = models.CharField(max_length=75)
	info = models.TextField(null=False, blank=False)
	when = models.DateTimeField(null=False, blank=False, auto_now_add=False)
	ends = models.DateTimeField(null=True, blank=True, auto_now_add=False)
	cover_price = models.DecimalField(decimal_places=2, max_digits=8, blank=True, null=True )
	cover_image = models.ImageField(null=True, blank=True, upload_to="media_event")
	EVENT_STATE = ( 
        ( 10 , 'Public' ), 
        ( 20 , 'Private' ), 
        ( 21 , 'Whit invitation' ),
        ( 12 , 'Public is coming' ), 
        ( 22 , 'Private is coming' ),
        ( 221, 'Private with invitation is coming'),
        ( 13 , 'Public Completed' ), 
        ( 23 , 'Private Completed' ),
        ( 14 , 'Public Canceled' ), 
        ( 24 , 'Private Canceled' ), 
        ( 244, 'Private with invitation is canceled' ),
    ) 
	state = models.IntegerField(
		choices=EVENT_STATE, 
		default=20)
	date_joined = models.DateField(auto_now_add=True)
	hashtags = models.ManyToManyField(Hashtag, blank=True)
	location = models.ForeignKey(Location, null=True, blank=False)
	user = models.ForeignKey(User)
	guests = models.ManyToManyField(User_profile, null=False, blank=True)
	def __unicode__(self):
		return unicode(self.event_name)

class Post(models.Model):
	date_joined = models.DateField(null=False, blank=False, auto_now_add=True)
	image = models.ImageField(upload_to="media_event", null=True, blank=True)
	description = models.CharField(max_length=200, null=True, blank=True )
	POST_STATE  =  ( 
		( 10 , 'Event image' ),
		( 20 , 'Commertial image' ), 
        ( 30 , 'Hashtag image' ),
    ) 
	state = models.IntegerField(choices=POST_STATE)
	event = models.ForeignKey(Event)
	user = models.ForeignKey(User)
	def __unicode__(self):
		return unicode(self.description)
	class Admin:
		list_display = ('commertial_name', 'user','ruc', 'location', 'date_joined')
		list_filter = ('commertial_name', 'user')

class Sponsor(models.Model):
	event = models.ForeignKey(Event)
	commertial = models.ForeignKey(Commertial)
	STATE  =  ( 
		( 10 , 'approved' ),
		( 20 , 'pending' ), 
    ) 
	state = models.IntegerField(choices=STATE, default=20)

Zolociones/Mape/views.py
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.template.context import RequestContext
from django.template import Context
from django.http import HttpResponse, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.db.models import Q 
from mapbox import Datasets

import datetime
from maccounts.models import User_profile
from maccounts.forms import EventRegisterForm, CommertialRegisterForm, LocationRegisterForm  
from .models import * #POST, Offer, Commertial_offer, Categorie, Commertial_categorie, Event, Sponsor, Hashtag
# Esta vista requiere que haya un usuario logeado
@login_required
def mape_view(request):
    #Descrip: Vista para la pantalla principal de la aplicacion Mape
    event_list = Event.objects.all()
    location_list = Location.objects.all()
    user_events = Event.objects.filter(user=request.user)
    zero_time = datetime.datetime.now()
    user_profile = User_profile.objects.filter(user=request.user)
    if user_profile:
        user_commertial = Commertial.objects.filter(user_profile=user_profile)
    else:
        user_commertial = None
    commertial_list = Commertial.objects.all()
    #dataset_id = 'citbo4r7007bl2slqj6cha0mq'
    #dataset = Datasets.read_dataset(dataset_id).json()
    context = ({"events": event_list, 
        "zero_time": zero_time,
        "base": 'base-mape.html',
        "user_events": user_events,
        "username": request.user.username,
        "commertials": commertial_list,
        "user_commertial": user_commertial,
        "MAPBOX_ACCESS_TOKEN": 'pk.eyJ1Ijoiem9sbyIsImEiOiJ0VlphRlZFIn0.gLAS81dTkxi1W5FqVMKwXg',
        })
    
    return render_to_response("mape/mape.html", context)

def search_view(request):
    query = request.GET.get('q','')
    zero_time = datetime.datetime.now()
    context = {"query": query}
    if query:
        qset_profiles = (
            Q(event_name__icontains=query) |
            Q(hashtag__icontains=query)
            )
        qset_events = (
            Q(user_name__icontains=query) 
            )
        qset_offers = (
            Q(offer__icontains=query) 
            )
        profiles = User_profile.objects.filter(qset_profiles).distinct()
        events = Event.objects.filter(qset_events).distinct()
        offers = Offer.objects.filter(qset_offers).distinct()
        context = { 
        "profiles": profiles, 
        "events": events, 
        "offers": offers,
        "query": query
        }
    return render_to_response("mape/search.html", context)

def shower_view(request):
    zero_time = datetime.datetime.now()
    """ se necesita mostrar los eventos: con prioridad 1.- Con incitacion publicos 2.- privados, con invitacion 3.- publicos para la semana 
    4.- Localidades comerciales con mas seguidores 5.- Localidades privadas """
    user_profile = User_profile.objects.get(user=request.user)
    events = Event.objects.all()
    invitation_events = Event.objects.filter(guests = user_profile).exclude(state=13)
    invitation_events_priv = invitation_events.filter(state=20)
    invitation_events_pub = invitation_events.exclude(state=20)
    """ la variable q contiene el texto de busqueda """
    query = request.GET.get(
        'q','')
    context = {
    "base": 'base-mape.html',
    "query": query,
    "invitation_events_priv": invitation_events_priv, 
    "events": events
    }
    if query:
        """ Uso de querysets para almacenar la consulta  Base de datos """ 
        qset_profiles = (
            Q(event_name__icontains=query) |
            Q(hashtag__icontains=query)
            )
        qset_events = (
            Q(user_name__icontains=query) 
            )
        qset_offers = (
            Q(offer__icontains=query) 
            )
        profiles = User_profile.objects.filter(qset_profiles).distinct()
        events = Event.objects.filter(qset_events).distinct()
        offers = Offer.objects.filter(qset_offers).distinct()
        context = { 
        "profiles": profiles, 
        "events": events, 
        "offers": offers,
        "query": query
        }
    return render_to_response("mape/shower_event.html", context)

def event_register_view(request):
    form = EventRegisterForm()
    if request.method == 'POST':
        """ request.FILES lo usamos para traer archivos como imagenes, video, sonido, etc"""
        form = EventRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            event_name = cleaned_data.get('event_name')
            info = cleaned_data.get('info')
            when = cleaned_data.get('when')
            ends = cleaned_data.get('ends')
            cover_price = cleaned_data.get('cover_price')
            cover_image = cleaned_data.get('cover_image')
            hashtags = cleaned_data.get('hashtags')
            location = cleaned_data.get('location')
            user = request.user
            profile_model = Profile.objects.get(user.id)
            new_event = Event()
            new_event.event_name = event_name
            new_event.info = info
            new_event.when = when
            new_event.ends = ends
            new_event.cover_price = cover_price
            new_event.cover_image = cover_image
            new_event.hashtags = hashtags
            new_event.location = location
            new_event.user = user
            """ new_event.guests = profile_model """
            new_event.save()
        else:
            form = EventRegisterForm()
    context = {'form': form}
    return render(request, 'mape/event_register.html', context)

def commertial_register_view(request):
    if request.method == 'POST':
        form = RegisterCommertialForm(request.POST, request.FILES)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        commertial_name = cleaned_data.get('name')
        description = cleaned_data.get('description')
        commertial_image = cleaned_data.get('commertial_image')
        price_initial = cleaned_data.get('price_initial')
        price_final = cleaned_data.get('price_final')
        username = cleaned_data.get('username')

def location_register_view(request):
    if request.GET:
        latitude = request.GET.get('latitude')
        longitude = request.GET.get('longitude')
        print latitude
    if request.method == 'POST':
        form = LocationRegisterForm(request.POST, request.FILES)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        location_name = cleaned_data.get('name')
        offers = cleaned_data.get('description')
        categories = cleaned_data.get('commertial_image')
        date_joined = cleaned_data.get('price_initial')
        image = cleaned_data.get('price_final')
        latitude = cleaned_data.get('username')
        longitude
        user_profile
        subscribers

def accounts_view(request):
    # Descrip: Vista para mostrar la configuracion de las cuentas del usuario
    user_profile = User_profile.objects.get(user=request.user)
    user_commertial = Commertial.objects.filter(user_profile=user_profile)
    full_name = request.user.get_full_name()
    context = ({
        "base": 'base.html',
        "user_commertial": user_commertial,
        "user_profile": user_profile,
        "full_name": full_name,
    })
    return render_to_response("mape/accounts.html", context)

Zolociones/Mape/templates/base-mape.html
<!-- Carga los archivos estaticos de la aplicacion-->
{% load staticfiles %}
<!-- -->
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <title>{% block title%}{% endblock title %}</title>
        <meta name="description" content="Mapa de eventos.">
        <meta name="keywords" content="maps, events, geo, html5, mobile, android, ios, tablet, smartphone, turism, ecuador, macas, morona">
        <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Comfortaa:400,700,300' rel='stylesheet' type='text/css'>
        <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
        <link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
        <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}" media="screen,projection">
        <link rel="stylesheet" href="{% static 'css/mape.css' %}" >
    </head>

    <body>
    <!-- Header -->
    <nav class="row no-margin no-padding">
        <div class="nav-wrapper cyan">
            <a class="brand-logo center" href="#"><h4>mape</h4></a>
            <!-- BOTON de menu izquierdo -->
            <ul id="nav-left" class="" >
                <li><a class="dropdown-button" data-activates="menu-izq"><i class="material-icons left">view_module</i><b class="hide-on-med-and-down"></b></a></li>
            </ul>
            <!-- BOTON de menu izquierdo -->
            <ul id="nav-right" class="">
                <li class="right"><a class="dropdown-button" data-activates="menu-der"><i class="material-icons ">perm_identity</i></a></li>
            </ul>
            <!-- LISTA de menu izquierdo -->
            <ul id="menu-izq" class="dropdown-content">
                <li><a href="{% url 'Mape:mapa' %}" class="center"> <i class="material-icons">language</i></a></li>
                <li class="divider"></li>
                <li><a href="{% url 'Mape:shower' %}" class="center"> <i class="material-icons">explicit</i>Eventos<span class="new badge cyan ">4</span></a></li>
            </ul>
            <!-- LISTA de menu derecho -->
            <ul id="menu-der" class="dropdown-content">
                <!-- Links genericos para cuentas comerciales -->
                {% if user_commertial %}
                <li><a href="" class="center"> <i class="material-icons">assignment_ind</i>{{ user_commertial.commertial_name }}</a></li>
                {% endif %}
                <li class="divider"></li>
                <li><a href="{% url 'Mape:accounts' %}" class="center"> <i class="material-icons">settings_applications</i>Configuraciones </a></li>
                <li><a href="{% url 'Maccounts:maccounts.logout' %}" class="center"> <i class="material-icons">power_settings_new</i>Salir</a></li>
            </ul>
        </div>
    </nav>
    <!-- tab de progreso -->
    <div class="cyan progress no-margin cyan lighten-3">
        <div class="indeterminate cyan"></div>
    </div>
    <div class="row no-padding no-margin" >
    {% block content %}
    {% endblock content %}
    </div>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    <script type="text/javascript">
            (function($){
            // Provide your access token
            L.mapbox.accessToken = '{{ MAPBOX_ACCESS_TOKEN }}';
            // Create a map in the div #map. coordenates by default: Macas-Ecuador
            var map = L.mapbox.map('map', 'mapbox.light', {
            }).setView([-78.12, 2.30], 9);

            // Set the coordenates if the navigator have geolocation
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position){
                  latitude= position.coords.latitude,
                  longitude = position.coords.longitude;
                  map.setView([latitude, longitude], 16)
                  });
                  }else{
                    console.log("No dispones de geolocalizacion en tu navegador");
                    alert("No dispones de geolocalizacion en tu navegador");
                  };
            var latitude,
              longitude;
            // Function at right click
            map.on('contextmenu', function(e) {
              latitude = e.latlng.lat;
              longitude = e.latlng.lng;
              console.log('latitude: ', + latitude + " longitude: " + longitude);
              $('#modal-event-register').openModal();
            });

            $("#register-location").click(function(){
                $(location).attr('href', '//127.0.0.1:8000/mape/location_register?latitude='+latitude+'&longitude='+longitude);
              });

            var tile = map.getTileJSON();

            L.mapbox.featureLayer({
                // this feature is in the GeoJSON format: see geojson.org
                // for the full specification
                type: 'Feature',
                geometry: {
                    type: 'Point',
                    // coordinates here are in longitude, latitude order because
                    // x, y is the standard for GeoJSON and many formats
                    coordinates: [
                      -1.67, -78.66
                    ]
                },
                properties: {
                    title: 'Peregrine Espresso',
                    description: '1718 14th St NW, Washington, DC',
                    // one can customize markers by adding simplestyle properties
                    // https://www.mapbox.com/guides/an-open-platform/#simplestyle
                    'marker-size': 'large',
                    'marker-color': '#BE9A6B',
                    'marker-symbol': 'cafe'
                }
            }).addTo(map);

            addCurrentLocationToMap = function() {
              if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position){
                  var lat= position.coords.latitude,
                  longit = position.coords.longitude;
                  console.log('--- Tu posision actual es: --- ');
                  console.log('Lat: ', + lat);
                  console.log('Long: ', + longit);
                  console.log('---------------------------');
                  var marker = L.marker([lat, longit], {
                    icon: L.mapbox.marker.icon({
                  'marker-size': 'large',
                  'marker-symbol': 'bus',
                  'marker-color': '#fa0'})
                  });
                  marker.addTo(map);
                  marker.bindPopup('Estas en: <br>' + lat + ', ' + longit).openPopup();
                });
              }else{
                console.log("No dispones de geolocalizacion en tu navegador")
              }
            };

            // 
            (function() {
              var wf = document.createElement('script');
              wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
                '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
              wf.type = 'text/javascript';
              wf.async = 'true';
              var s = document.getElementsByTagName('script')[0];
              s.parentNode.insertBefore(wf, s);
            })// end of document ready
            })(jQuery); 
            //// end of jQuery name space
            $("#CurrentLocation").click(addCurrentLocationToMap);//Mapbox: hubicacion actual (D)
        </script>
    <script src="{% static 'js/mapbox-jquery.js' %}"></script>
    <script src="{% static 'js/rango-mape.js' %}"></script>
    </body>
</html>