Zolociones/Mape/urls.py
from django.conf.urls import url
from maccounts.views import login_view, logout_view
from . import views

urlpatterns = [
    # ex: /mape/
    url(r'^$', views.mape_view, name='mapa'),
    url(r'^login/$', login_view, name='login'),
    url(r'^accounts/$', views.accounts_view, name='accounts'),
    url(r'^e/$', views.shower_view, name='shower'),
    url(r'^event_register/$', views.event_register_view, name='event_register'),
    url(r'^location_register/$', views.location_register_view, name='location_register'),
    url(r'^commertial_register/$', views.commertial_register_view, name='commertial_register'),
    url(r'^$search/$', views.search_view, name='search'),
    url(r'^$logout/$', logout_view, name='maccounts.logout'),
]

Zolociones/Zolociones/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^mape/', include('Mape.urls', namespace="Mape")),
    url(r'^login/', include('maccounts.urls', namespace="Maccounts")),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
        }),
    ]

Zolociones/Mape/models.py
from django.db import models
from django.contrib.auth.models import User, Group
import datetime
from django.utils import timezone
from maccounts.models import User_profile

class Hashtag(models.Model):
	hashtag_name = models.CharField(max_length=45)
	def __unicode__(self):
		return unicode(self.hashtag_name)

class Categorie(models.Model):
	categorie_name = models.CharField(max_length=45, unique=True)
	def __unicode__(self):
		return unicode(self.categorie_name)

class Offer(models.Model):
	offer_name = models.CharField(max_length=45, unique=True)
	price = models.DecimalField(decimal_places=2, max_digits=8, blank=True, null=True )
	product = models.BooleanField(default=True, blank=True)
	image = models.ImageField(upload_to="media", null=True, blank=True)
	def __unicode__(self):
		return unicode(self.offer_name)

class Location(models.Model):
	location_name = models.CharField(max_length=45)
	offers = models.ManyToManyField(Offer, blank=True)
	categories = models.ManyToManyField(Categorie)
	date_joined = models.DateField(null=False, blank=False, auto_now_add=True)
	image = models.ImageField(upload_to="media", null=True, blank=True)
	latitude = models.DecimalField(null=True, decimal_places=15, max_digits=19)
	longitude = models.DecimalField(null=True, decimal_places=15, max_digits=19)
	user_profile = models.ForeignKey(User)
	subscribers = models.ManyToManyField(User_profile, null=False, blank=True)
	def __unicode__(self):
		return unicode(self.location_name)

class Commertial(models.Model):
	commertial_name = models.CharField(max_length=45, unique=True)
	location = models.OneToOneField(Location, on_delete=models.CASCADE)
	ruc = models.BigIntegerField(blank=True, null= True)
	description = models.TextField(null=False, blank=False)
	date_joined = models.DateField(null=False, blank=False, auto_now_add=True)
	commertial_image = models.ImageField(upload_to="accounts", null=True, blank=True)
	user_profile = models.OneToOneField(User_profile)
	def __unicode__(self):
		return unicode(self.commertial_name)

class Event(models.Model):
	event_name = models.CharField(max_length=75)
	info = models.TextField(null=False, blank=False)
	when = models.DateTimeField(null=False, blank=False, auto_now_add=False)
	ends = models.DateTimeField(null=True, blank=True, auto_now_add=False)
	cover_price = models.DecimalField(decimal_places=2, max_digits=8, blank=True, null=True )
	cover_image = models.ImageField(null=True, blank=True, upload_to="media_event")
	EVENT_STATE = ( 
        ( 10 , 'Public' ), 
        ( 20 , 'Private' ), 
        ( 21 , 'Whit invitation' ),
        ( 12 , 'Public is coming' ), 
        ( 22 , 'Private is coming' ),
        ( 221, 'Private with invitation is coming'),
        ( 13 , 'Public Completed' ), 
        ( 23 , 'Private Completed' ),
        ( 14 , 'Public Canceled' ), 
        ( 24 , 'Private Canceled' ), 
        ( 244, 'Private with invitation is canceled' ),
    ) 
	state = models.IntegerField(
		choices=EVENT_STATE, 
		default=20)
	date_joined = models.DateField(auto_now_add=True)
	hashtags = models.ManyToManyField(Hashtag, blank=True)
	location = models.ForeignKey(Location, null=True, blank=False)
	user = models.ForeignKey(User)
	guests = models.ManyToManyField(User_profile, null=False, blank=True)
	def __unicode__(self):
		return unicode(self.event_name)

class Post(models.Model):
	date_joined = models.DateField(null=False, blank=False, auto_now_add=True)
	image = models.ImageField(upload_to="media_event", null=True, blank=True)
	description = models.CharField(max_length=200, null=True, blank=True )
	POST_STATE  =  ( 
		( 10 , 'Event image' ),
		( 20 , 'Commertial image' ), 
        ( 30 , 'Hashtag image' ),
    ) 
	state = models.IntegerField(choices=POST_STATE)
	event = models.ForeignKey(Event)
	user = models.ForeignKey(User)
	def __unicode__(self):
		return unicode(self.description)
	class Admin:
		list_display = ('commertial_name', 'user','ruc', 'location', 'date_joined')
		list_filter = ('commertial_name', 'user')

class Sponsor(models.Model):
	event = models.ForeignKey(Event)
	commertial = models.ForeignKey(Commertial)
	STATE  =  ( 
		( 10 , 'approved' ),
		( 20 , 'pending' ), 
    ) 
	state = models.IntegerField(choices=STATE, default=20)

Zolociones/Mape/views.py
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.template.context import RequestContext
from django.template import Context
from django.http import HttpResponse, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.db.models import Q 
from mapbox import Datasets

import datetime
from maccounts.models import User_profile
from maccounts.forms import EventRegisterForm, CommertialRegisterForm, LocationRegisterForm  
from .models import * #POST, Offer, Commertial_offer, Categorie, Commertial_categorie, Event, Sponsor, Hashtag
# Esta vista requiere que haya un usuario logeado
@login_required
def mape_view(request):
    #Descrip: Vista para la pantalla principal de la aplicacion Mape
    event_list = Event.objects.all()
    location_list = Location.objects.all()
    user_events = Event.objects.filter(user=request.user)
    zero_time = datetime.datetime.now()
    user_profile = User_profile.objects.filter(user=request.user)
    if user_profile:
        user_commertial = Commertial.objects.filter(user_profile=user_profile)
    else:
        user_commertial = None
    commertial_list = Commertial.objects.all()
    #dataset_id = 'citbo4r7007bl2slqj6cha0mq'
    #dataset = Datasets.read_dataset(dataset_id).json()
    context = ({"events": event_list, 
        "zero_time": zero_time,
        "base": 'base-mape.html',
        "user_events": user_events,
        "username": request.user.username,
        "commertials": commertial_list,
        "user_commertial": user_commertial,
        "MAPBOX_ACCESS_TOKEN": 'pk.eyJ1Ijoiem9sbyIsImEiOiJ0VlphRlZFIn0.gLAS81dTkxi1W5FqVMKwXg',
        })
    
    return render_to_response("mape/mape.html", context)

def search_view(request):
    query = request.GET.get('q','')
    zero_time = datetime.datetime.now()
    context = {"query": query}
    if query:
        qset_profiles = (
            Q(event_name__icontains=query) |
            Q(hashtag__icontains=query)
            )
        qset_events = (
            Q(user_name__icontains=query) 
            )
        qset_offers = (
            Q(offer__icontains=query) 
            )
        profiles = User_profile.objects.filter(qset_profiles).distinct()
        events = Event.objects.filter(qset_events).distinct()
        offers = Offer.objects.filter(qset_offers).distinct()
        context = { 
        "profiles": profiles, 
        "events": events, 
        "offers": offers,
        "query": query
        }
    return render_to_response("mape/search.html", context)

def shower_view(request):
    zero_time = datetime.datetime.now()
    """ se necesita mostrar los eventos: con prioridad 1.- Con incitacion publicos 2.- privados, con invitacion 3.- publicos para la semana 
    4.- Localidades comerciales con mas seguidores 5.- Localidades privadas """
    user_profile = User_profile.objects.get(user=request.user)
    events = Event.objects.all()
    invitation_events = Event.objects.filter(guests = user_profile).exclude(state=13)
    invitation_events_priv = invitation_events.filter(state=20)
    invitation_events_pub = invitation_events.exclude(state=20)
    """ la variable q contiene el texto de busqueda """
    query = request.GET.get(
        'q','')
    context = {
    "base": 'base-mape.html',
    "query": query,
    "invitation_events_priv": invitation_events_priv, 
    "events": events
    }
    if query:
        """ Uso de querysets para almacenar la consulta  Base de datos """ 
        qset_profiles = (
            Q(event_name__icontains=query) |
            Q(hashtag__icontains=query)
            )
        qset_events = (
            Q(user_name__icontains=query) 
            )
        qset_offers = (
            Q(offer__icontains=query) 
            )
        profiles = User_profile.objects.filter(qset_profiles).distinct()
        events = Event.objects.filter(qset_events).distinct()
        offers = Offer.objects.filter(qset_offers).distinct()
        context = { 
        "profiles": profiles, 
        "events": events, 
        "offers": offers,
        "query": query
        }
    return render_to_response("mape/shower_event.html", context)

def event_register_view(request):
    form = EventRegisterForm()
    if request.method == 'POST':
        """ request.FILES lo usamos para traer archivos como imagenes, video, sonido, etc"""
        form = EventRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            event_name = cleaned_data.get('event_name')
            info = cleaned_data.get('info')
            when = cleaned_data.get('when')
            ends = cleaned_data.get('ends')
            cover_price = cleaned_data.get('cover_price')
            cover_image = cleaned_data.get('cover_image')
            hashtags = cleaned_data.get('hashtags')
            location = cleaned_data.get('location')
            user = request.user
            profile_model = Profile.objects.get(user.id)
            new_event = Event()
            new_event.event_name = event_name
            new_event.info = info
            new_event.when = when
            new_event.ends = ends
            new_event.cover_price = cover_price
            new_event.cover_image = cover_image
            new_event.hashtags = hashtags
            new_event.location = location
            new_event.user = user
            """ new_event.guests = profile_model """
            new_event.save()
        else:
            form = EventRegisterForm()
    context = {'form': form}
    return render(request, 'mape/event_register.html', context)

def commertial_register_view(request):
    if request.method == 'POST':
        form = RegisterCommertialForm(request.POST, request.FILES)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        commertial_name = cleaned_data.get('name')
        description = cleaned_data.get('description')
        commertial_image = cleaned_data.get('commertial_image')
        price_initial = cleaned_data.get('price_initial')
        price_final = cleaned_data.get('price_final')
        username = cleaned_data.get('username')

def location_register_view(request):
    if request.GET:
        latitude = request.GET.get('latitude')
        longitude = request.GET.get('longitude')
        print latitude
    if request.method == 'POST':
        form = LocationRegisterForm(request.POST, request.FILES)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        location_name = cleaned_data.get('name')
        offers = cleaned_data.get('description')
        categories = cleaned_data.get('commertial_image')
        date_joined = cleaned_data.get('price_initial')
        image = cleaned_data.get('price_final')
        latitude = cleaned_data.get('username')
        longitude
        user_profile
        subscribers

def accounts_view(request):
    # Descrip: Vista para mostrar la configuracion de las cuentas del usuario
    user_profile = User_profile.objects.get(user=request.user)
    user_commertial = Commertial.objects.filter(user_profile=user_profile)
    full_name = request.user.get_full_name()
    context = ({
        "base": 'base.html',
        "user_commertial": user_commertial,
        "user_profile": user_profile,
        "full_name": full_name,
    })
    return render_to_response("mape/accounts.html", context)

Zolociones/Mape/templates/mape/accounts.html
{% extends base %}
{% block title %}Configuracion{% endblock title %}
{% block name %}Cuentas{% endblock name %}
{% block back_url %}{% url 'Mape:mapa' %}{% endblock back_url %}
{% block back_logo %}home{% endblock back_logo %}

{% block content %}
<!-- INICIA EL BLOQUE DE CONTENIDO -->
<div class="container center">
    <br>
    <div class="row " >
        <!-- SI EXISTE FOTO DE PERFIL EN PERFIL DE USUARIO -->
        {% if user_profile.image %}
            <img class="col l2 s4 responsive-img circle materialboxed" width="120" src="{{ MEDIA_URL }}{{ user_profile.image.url }}" alt="Foto de perfil: {{ user_profile.user_name }}">
        {% else %}
            <a class="col l2 s3 button waves-effect">
                <i class="material-icons large prefix cyan-text" alt="Imagen de {{ user_profile.user_name }}">account_circle</i>
            </a>
        {% endif %}
        <div class="col l3 s8 ">
            <p>
            Usuario: {{ user_profile.user_name }} <br>
            {% if user_commertial %}
            Anfitri&oacute;n de: <a href="">{{ user_commertial.commertial_name }}</a><br>
            {% endif%}
            {% if user_profile.phone_1 %}
            Celular: {{ user_profile.phone_1 }}<br>
            {% endif%}
            {% if user_profile.phone_2 %}
            Contacto 2: {{ user_profile.phone_2 }}<br>
            {% endif%}
        </div>
    </div>
    
    <div class="divider"></div>
    <!-- COMIENZA EL BLOQUE QUE CONTIENE LA INFORMACION DEL PERFIL DE USUARIO -->
    <div class="right">
        <a href="{% url 'Maccounts:maccounts.user_register' %}"><i class="material-icons">mode_edit</i><b>Editar</b></a>
    </div>
    <div class="card-panel lighten-5 z-depth-1 section row">
        <h5 class="col l3 s12 text-center">M&aacute;s informaci&oacute;n: </h5>
        <p class="col l5 s12">
            Nombre: {{ full_name }}<br>
            Email: {{ user_profile.user.email }} <br>
            {% if user_commertial %}
                C&eacute;dula: {{ user_profile.identification }} <br>
            {% endif %}
            Activo desde: {{ user_profile.user.date_joined }} <br>
        </p>
    </div>
    <!-- EXISTE UN COMERCIAL ASOCIADO A LA CUENTA SE MUESTRA A CONTINUACION-->
    <div class="divider"></div>
    {% if user_commertial %}
    <div class="right">
            <a href="#" ><i class="material-icons">mode_edit</i><b>Editar</b></a>
        </div>
    <div class=" card-panel lighten-5 z-depth-1 section row">
        <!-- ojo aqui la suma del row= col1 + col2 + offset-l -->
        <h5 class="col l3"> {{ user_commertial.commertial_name }}: </h5>
        <img class="col l2 s3 responsive-img circle materialboxed" width="120" src="http://lorempixel.com/250/250/nature/2" alt="Im&aacute;gen de: {{ user_commertial.commertial_name }}">
        categoria 1 <br>
        {% for categorie in categories %}
            {{categorie}} ,
        {% endfor %}
        {% if user_commertial.ruc %}
        Ruc: {{ user_commertial.ruc }}
        {%endif%}
        {{ user_commertial.description }} <br>
        
    </div>
    {% endif %}
    </ul>
</div>

    
        
{% endblock content %}

Zolociones/Mape/templates/mape/event_register.html
{% extends 'base.html' %}
{% block title %}Event{% endblock title %}
{% block name %}Registro{% endblock name %}
{% block back_url %}{% url 'Mape:mapa' %}{% endblock back_url %}
{% block back_logo %}skip_previous{% endblock back_logo %}
{% block content %}
    {% if mensaje %}
        <div class="alert alert-danger">
            {{ mensaje }}
        </div>
    {% endif %} 
        <!-- Ventana de registro -->
        <div class="section container">
            <form action="" method="post" class="center-align" style="padding-top: 0;">
            	{% csrf_token %}
                <div class="form-group input-field col s12 l6">
                    <input id="event_name" name="event_name" class=" input-text black-text darken-3 validate" type="text" length="75"/>
                    <label for="event_name" class="black-text darken-3">Nombre del evento</label>
                </div>
                <div class="form-group input-field col s12 l6">
                    <textarea id="info" name="info" class=" black-text darken-3 materialize-textarea validate"/></textarea>
                    <label for="info" data-error="wrong" data-success="right" class="black-text darken-3">Informaci&oacute;n del evento</label>
                </div>
                <div class="form-group input-field col s4 l3 m4">
                    <input id="when" name="when" class=" black-text darken-3 datepicker validate" type="date" />
                    <label for="ends" class="black-text darken-3">Fecha de inicio</label>
                </div>
                <div class="form-group input-field col s4 l3 m4">
                    <input id="ends" name="ends" class=" black-text darken-3 validate" type="number" />
                    <label for="ends" class="black-text darken-3">Duraci&oacute;n</label>
                </div>
                <div class="form-group input-field col s6">
                    <input id="cover_price" name="cover_price" class=" black-text darken-3 validate" type="number" />
                    <label for="cover_price" class="black-text darken-3">Precio de entrada | cover</label>
                </div>
                <div class="form-group file-field input-field">
                    <div class="btn cyan">
                        <span> Im&aacute;gen </span>
                        <input id="cover_image" name="cover_image" class=" black-text darken-3" type="file" />
                    </div>
                    <div class="file-path-wrapper">
                        <input class="file-path validate" type="text" placeholder="Imagen del evento | afiche"/>
                    </div>
                </div>
                <div class="form-group input-field col s6">
                    <input id="hashtags" name="hashtags" class=" black-text darken-3 autocomplete" type="text" />
                    <label for="hashtags" class="black-text darken-3">Etiquetas | Hashtags</label>
                </div>
                <div class="form-group input-field col s6">
                    <input id="location" value="{{latitude}} {{longitude}}" name="location" class="disabled black-text darken-3" type="text" />
                    <label for="location" class="black-text darken-3">Location</label>
                </div>
                <button class="btn cyan marginado darken-1 waves-effect waves-light " type="submit" name="action">Listo
                    <i class="material-icons">send</i>
                </button>
            </form>
        </div>
{% endblock content %}

Zolociones/Mape/templates/mape/logout.html
logout.html

Zolociones/Mape/templates/mape/mape.html
{% extends 'base-mape.html' %}
{% block title %}Mape{% endblock title %}
{% block content %}

<div class="no-padding">
    <!-- Mapa-->
    <div id="Mapa" class="col s12 no-padding">
        <!-- Contenedor de mapa-->
        <div id="map">
            <!-- Contenedor de opciones al frente del mapa-->
            <div class="col s12 left frente">
                <!-- Boton my-location-->
                <div class="col s4 right right-align tooltipped" data-position="bottom" data-delay="2" data-tooltip="Mi ubicacion">
                    <a href="#" id="CurrentLocation">
                        <i class="material-icons medium ">my_location</i>
                    </a>
                </div>
                <!-- Barra de busqueda-->
                <div class="input-field right col s6 l3 offset-l2">
                    <i class="material-icons prefix cyan-text">search</i>
                    <input id="search1" type="search" class="validate">
                    <label for="search1">buscar</label>
                </div>
                <!-- Boton añadir  -->
                <div class="no-padding">
                    <div class="fixed-action-btn" >
                        <a class="btn-floating btn-large cyan darken-2">
                            <i class="material-icons medium">add</i>
                        </a>
                        <ul>
                            <!-- Link para localidad --> 
                            <li><a class="btn-floating cyan darken-1 tooltipped" data-position="left" data-delay="2" data-tooltip="sitio"><i class="material-icons">room</i></a></li>
                            <!-- Link para evento -->
                            <li><a href="{% url 'Mape:event_register' %}" class="btn-floating red darken-1 tooltipped" data-position="left" data-delay="2" data-tooltip="evento"><i class="material-icons">room</i></a></li>
                        </ul>
                    </div>
                </div>
               
            </div>
        </div>
    </div>
     <!-- Modal Structure -->
    <div id="modal-event-register" class="modal">
        <div class="modal-content center">
            <h4> Opciones de mapa </h4>
            <p> Aseg&uacute;rese de que ha seleccionado la ubicaci&oacute;n ex&aacute;cta si desea registrar: </p>
            <a href="#!" id="register-location" class="btn cyan"> <i class="material-icons left  ">store</i> Una localidad </a>
            <br/>
            <a href="#!" id="register-event" class="btn cyan"> <i class="material-icons left  ">room</i> Un Evento </a>
            <div class="modal-footer">
                <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Cancelar</a>
            </div>
        </div>
        
    </div>

{% endblock content %}

Zolociones/Mape/templates/mape/shower_event.html
<!-- visualizador de eventos, localidades -->
{% extends base %}
{% block title %}Mape{% endblock title %}
{% block content %}
<div class="col s12 no-padding">
  <div id="Eventos" class="col s12 no-padding">
    <!-- Ciudad en la que se encuentra -->
    <div class="grey-text col s4 m4 l3 center">
        <p><h5>Macas</h5></p>
    </div>
    <!-- Boton de Busqueda -->
    <div class="cyan-text input-field col s7 m4 l3 ">
        <i class="material-icons prefix cyan-text">search</i>
        <input id="search2" type="search" class="validate no-padding">
        <label for="search2"><i class="material-icons prefix">buscar</i><label>
    </div>
    <!-- Boton añadir  -->
    {% if events %}
    <div class="no-padding">
        <div class="fixed-action-btn" >
            <a class="btn-floating btn-large cyan darken-2">
                <i class="material-icons medium">add</i>
            </a>
            <ul>
                <li><a href="{% url 'Mape:location_register' %}" class="btn-floating cyan darken-1 tooltipped" data-position="left" data-delay="2" data-tooltip="sitio"><i class="material-icons">room</i></a></li>
                <li><a href="{% url 'Mape:event_register' %}" class="btn-floating red darken-1 tooltipped" data-position="left" data-delay="2" data-tooltip="evento"><i class="material-icons">room</i></a></li>
            </ul>
        </div>
    </div>
    {% endif %}
        <!-- Enlistador de eventos -->
        {% for event in events %}
        <div class="card large cyan-text col s12 center l8 offset-l2">
          <!-- Slider de la tarjeta -->
              <div class="card-image no-margin waves-effect waves-block waves-light slider activator">
                  <ul class="slides">
                    <li>
                      <img src="http://lorempixel.com/580/250/nature/2"> <!-- random image -->
                      <div class="caption center-align">
                        <h3>{{ event.event_name }}</h3>
                        <h5 class="light grey-text text-lighten-3"> Un evento de: <br>{{ event.user.username }}.</h5>
                      </div>
                    </li>
                    {% if  event.hashtags %}
                    <li>
                      <img src="http://lorempixel.com/580/250/nature/3"> <!-- imagen de hashtag si hay -->
                      <div class="caption left-align">
                        <h3>Left Aligned Caption</h3>
                        <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
                      </div>
                    </li>
                    <li>
                      <img src="http://lorempixel.com/580/250/nature/3"> <!-- random image -->
                      <div class="caption right-align">
                        <h3>Right Aligned Caption</h3>
                        <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
                      </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- opciones de la tarjeta-->
            <div class="card-content no-margin no-padding">
              <span class="card-title activator grey-text text-darken-4">{{ event.event_name }}<i class="material-icons right">more_vert</i></span>
              <p><a href="#">seguir</a></p>
            </div>
            <!-- Contenido revelado de la tarjeta del Evento-->
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4">{{ event.event_name }}<i class="material-icons right">close</i></span>
              <p>{{ event.info }}.</p>
              <ul class="collection filme-med">
                  <li class="collection-item">Lugar: {{ event.location }} </li>
                  <li class="collection-item">Hora: <b>{{ event.when }}</b></li>
                  {% if event.ends %}
                    <li class="collection-item">Hasta: <b>{{ event.ends }}</b></li>
                  {% endif %}
                  <li class="collection-item"><img class="materialboxed" width="400" src="http://lorempixel.com/580/250/nature/3"></li>
                  <li class="collection-item">Cover: 
                    <b>
                    {%if event.cover_price %} 
                      {{ event.cover_price }}
                    {% else %} GRATIS 
                    {% endif %}</b></li>
                  <li class="collection-item center">
                    <a class="btn-floating blue"><i class="material-icons medium">done</i> Seguir </a>
                  </li>
              </ul>
            </div>
          </div>
        {% endfor %}
    </div>
    <!-- visualizador popout tranparente 
    <ul class="collapsible popout" data-collapsible="accordion">
        <li>
            <div class="collapsible-header filme"><i class="material-icons right">room</i>
                <b>{{ base }}</b>
            </div>
            <div class="collapsible-body frente">
                <ul class="collection filme-med">
                    <li class="collection-item row">
                        <div class="col s6">
                        De: <b>{{ username }}</b></div> 
                    </li>
                     {% for event in events %}
                    <li class="collection-item row">
                        <div class="col s6">
                            <b>{{ event }}</b>
                    </li>
                    {% endfor %}
                    {% if user_events %}
                    <b>Tus eventos: </b>
                    {% for event in user_events %}
                    <li class="collection-item row">
                        <div class="col s6">
                            <b> {{ event }}</b>
                    </li>
                    {%endfor%}
                    {%endif%}
                    <li class="collection-item">Hora: <b>15h30</b></li>                            
                    <li class="collection-item truncate">Descripci&oacute;n: asdasdf asdfasdf   asdf asdasd asdfa asdf      ASDFASDFASDFASDF      ASDFASDFASDFA       asdf adf aSDFASDF ASDF</li>
                    <li class="collection-item"><img class="materialboxed" width="400" src="img/fiesta.jpg"></li>
                    <li class="collection-item">Cover: <b>free</b></li>
                    <li class="collection-item center"><a class="btn-floating blue"> <i class="material-icons medium">done</i></a><div class="separator"></div><a class="btn-floating blue"><i class="material-icons medium">add</i></a></li>
                </ul>
            </div>
        </li>
    </ul> -->
</div>
{% endblock content %}